language: python
python:
  - 2.7
env:
  - TOX_ENV=py33
  - TOX_ENV=py32
  - TOX_ENV=py27
  - TOX_ENV=py26
  - TOX_ENV=docs
install:
  - pip install --use-mirrors tox coveralls
script:
  tox -e $TOX_ENV
# notifications:
#   irc:
#     channels: "irc.freenode.org#paramiko"
#     template:
#       - "%{repository}@%{branch}: %{message} (%{build_url})"
#     on_success: change
#     on_failure: change
#     use_notice: true
#   email: false
after_success:
  - coveralls
